export const HERO_COUNTUP_DURATION_MS = 1400;

export const STAT_TILE_REVEAL_STEP_MS = 60;

export const STAGE_CARD_REVEAL_STEP_MS = 60;

export const COMPARISON_BAR_OPTIMIZED_DELAY_OFFSET_MS = 120;

export const COMPARISON_BAR_TOKENS_ROW_DELAY_MS = 120;
